swagger: "2.0"
info:
  description: "Demo Swagger/OpenAPI"
  version: "1.0.0"
  title: "Cliente"
host: "wiremockagl.azurewebsites.net"
basePath: "/"

schemes:
- "https"
- "http"
paths:
  /cliente:
    get:
      tags:
      - "cliente"
      summary: "Lista clientes"
      description: ""
      operationId: "getClientes"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Clientes"
    post:
      tags:
      - "cliente"
      summary: "Insere um novo cliente"
      description: ""
      operationId: "addCliente"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Novo cliente"
        required: true
        schema:
          $ref: "#/definitions/Cliente"
      responses:
        "405":
          description: "Invalid input"
      security:
        - api_key: []
    put:
      tags:
      - "cliente"
      summary: "Update cliente"
      description: ""
      operationId: "updatecliente"
      consumes:
      - "application/json"
      produces:
      - "application/xml"
      parameters:
      - in: "body"
        name: "body"
        description: "cliente"
        required: true
        schema:
          $ref: "#/definitions/Cliente"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Cliente not found"
        "405":
          description: "Validation exception"
      security:
        - api_key: []
  /cliente/{Id}:
    get:
      tags:
      - "cliente"
      summary: "Find cliente by ID"
      description: "Returns a single cliente"
      operationId: "getClienteById"
      produces:
      - "application/json"
      parameters:
      - name: "Id"
        in: "path"
        description: "ID of cliente to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Cliente"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Cliente not found"
      security:
      - api_key: []

    delete:
      tags:
      - "cliente"
      summary: "Deletes cliente"
      description: ""
      operationId: "deleteCliente"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "Id"
        in: "path"
        description: "Id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Cliente not found"
      security:
        - api_key: []

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Cliente:
    type: "object"
    required:
    - "nome"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "José Silva"
      status:
        type: "string"
        description: "Cliente status"
        enum:
        - "Ativo"
        - "Inativo"
  Clientes:
    type: array
    items:
      $ref: '#/definitions/Cliente'
      
